Brandon/reward handler fixes
cmu-rl/malmo pull request #16
Opened 2019-10-02 23:09 UTC by brandonhoughton

Fixes the reward loop

2019-10-03 17:11 UTC, MadcowD requested changes

2019-10-03 17:11 UTC, MadcowD commented on Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForPossessingItemImplementation.java
> +    // These events are double counted when performed by agents
Why are these commented.

2019-10-03 17:11 UTC, MadcowD commented on Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForPossessingItemImplementation.java
> +                    System.out.println(String.format("LOGTOPY:%s_%d.%d.%d.%d", item_stack.getUnlocalizedName(), savedCollected, maxCollected, nowCollected, matcher.matchSpec.getAmount()));
Why is there a LOG TO PY here? This is a debutg statement.

2019-10-03 17:17 UTC, ghost requested changes

2019-10-03 17:17 UTC, minerllabs commented on Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForPossessingItemImplementation.java
> +                    System.out.println(String.format("LOGTOPY:%s_%d.%d.%d.%d", item_stack.getUnlocalizedName(), savedCollected, maxCollected, nowCollected, matcher.matchSpec.getAmount()));
Remove logging

2019-10-03 17:17 UTC, minerllabs commented on Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForPossessingItemImplementation.java
> +    // These events are double counted when performed by agents
Compress commented information

2019-10-04 02:12 UTC, ghost approved these changes

2019-10-04 02:13 UTC, minerllabs commented
@MadcowD please review and merge!

2019-10-05 22:32 UTC, MadcowD approved these changes

2019-10-05 22:32 UTC, merged